### ISSUE TITLE
Uploading large (>100MB) files

### ISSUE THREAD

**Issue by matt-dray** [co-analysis/mwmi.govuk.data#1]
Hi Josh, I assume you know this but I just noticed that the daily action in this repo has been failing due to large file sizes (~200MB, where the GitHub limit is 100MB). There might be a few ways round this, but I happened to be looking at [the {piggyback} package](https://docs.ropensci.org/piggyback/) recently; there was [a talk about it](https://github.com/tanho63/project_immortality) at the recent RStudio conference.

**Comment by matt-dray** [comment]
Incidentally, looks like the workflows have been running for about half an hour before they fail. It's possible to add `timeout-minutes` to your workflow YAML if you like, which will stop them after a certain threshold. I think the free tier of GitHub has only a 2000-minute allowance, but I don't think co-analysis exceeds the threshold yet because few other repos use actions and e.g. {a11ytables} only does it on push.

**Comment by jwallace-co** [comment]
Cheers Matt - in this case it's an error in the data (files should not be this large, they've uploaded a .csv with about 19000 blank rows) so I'm not aiming to add in functionality that can process them - helpful to know there are some options though
